takoikatakotako/charalarm-backend

- application/handler/alarm_update/alarm_update.go
- application/repository/dynamodb.go
- application/repository/dynamodb_test.go
- application/service/alarm.go
- terraform/web_api/resource_alarm.tf
- terraform/web_api/resource_alarm_add.tf
- terraform/web_api/resource_alarm_delete.tf
- terraform/web_api/resource_alarm_edit.tf
- terraform/web_api/resource_alarm_list.tf
- terraform/web_api/resource_push_token.tf
- terraform/web_api/resource_push_token_ios.tf
- terraform/web_api/resource_push_token_ios_push.tf
- terraform/web_api/resource_push_token_ios_push_add.tf
- terraform/web_api/resource_push_token_ios_voip_push.tf
- terraform/web_api/resource_push_token_ios_voip_push_add.tf
> エンドポイントを追加

- application/converter/converter.go
- application/converter/converter_test.go
- application/handler/user_info/user_info.go
- application/response/push_token_response.go
- application/response/user_info_response.go
- application/service/user.go
- document/api-endpoint.md
> userInfoを実装

- application/converter/converter.go
- application/converter/converter_test.go
- application/entity/user.go
- application/handler/user_signup/user_signup.go
- application/request/anonymous_user_request.go
- application/request/user_signup.go
- application/response/user_info_response.go
- application/service/alarm.go
- application/service/push_token.go
- application/service/user.go
- document/api-endpoint.md
- document/dynamodb.md
- test/entity/signup_request.go
- test/entity/user_info_response.go
- test/entity/withdraw_request.go
- test/main_test.go
> userTokenをauthTokenに置き換えた

- .github/workflows/deploy-web-api-in-sandbox.yml
- application/handler/user_withdraw/user_withdraw.go
> 任意のブランチをSandboxにデプロイできるようにした。

- .github/workflows/deploy-web-api-in-sandbox.yml
- application/handler/user_signup/user_signup.go
- application/message/message.go
- script/build-deploy.sh
GitHubAction のバグを修正したら直った
close #35
> signupエンドポイントを使ってユーザー登録ができない

- application/database/alarm.go
- application/handler/alarm_add/alarm_add.go
- application/handler/alarm_delete/alarm_delete.go
- application/handler/alarm_edit/alarm_edit.go
- application/handler/alarm_list/alarm_list.go
- application/message/message.go
- application/repository/dynamodb.go
- application/response/alarm.go
- document/api-endpoint.md
> アラーム周りのリファクタリングとドキュメント更新

- application/entity/chara.go
- application/handler/batch/batch.go
- application/repository/dynamodb.go
- application/repository/sns.go
- application/repository/sns_test.go
- application/repository/sqs.go
- application/repository/sqs_test.go
- application/service/batch.go
- application/service/batch_test.go
- application/sqs/alarm_info.go
- terraform/batch/iam.tf
> BatchでSQSにキューを送る

- application/converter/converter.go
- application/converter/converter_test.go
- application/repository/sqs.go
- application/repository/sqs_test.go
- application/service/batch_test.go
> Batchのテストを作成

- application/handler/batch/batch.go
- application/handler/worker/worker.go
- application/repository/sqs.go
- application/service/batch.go
- application/service/worker.go
- script/build-deploy.sh
- terraform/worker/iam.tf
> VoIPプシュが飛ぶところまで実装

- README.md
- document/chara-resource.md
- document/chara.md
> キャラクター周りのリソースを設定、ドキュメント作成

- application/converter/converter.go
- application/converter/converter_test.go
- application/handler/push_token_ios_push_add/push_token_ios_push_add.go
- application/repository/dynamodb_alarm_test.go
- application/repository/environment_variable.go
- application/request/alarm.go
- application/service/alarm.go
- application/service/alarm_test.go
- application/service/batch.go
- application/service/batch_test.go
- application/service/chara.go
- application/service/push_token_test.go
- application/validator/alarm_validator.go
- terraform/batch/main.tf
- terraform/batch/variables.tf
- terraform/main.tf
- terraform/web_api/lambda_function/main.tf
- terraform/web_api/lambda_function/variables.tf
- terraform/web_api/resource_alarm_add.tf
- terraform/web_api/resource_alarm_delete.tf
- terraform/web_api/resource_alarm_edit.tf
- terraform/web_api/resource_alarm_list.tf
- terraform/web_api/resource_chara_id.tf
- terraform/web_api/resource_chara_list.tf
- terraform/web_api/resource_healthcheck.tf
- terraform/web_api/resource_push_token_ios_push_add.tf
- terraform/web_api/resource_push_token_ios_voip_push_add.tf
- terraform/web_api/resource_user_info.tf
- terraform/web_api/resource_user_signup.tf
- terraform/web_api/resource_user_withdraw.tf
> AlarmValidatorの不具合を修正

- application/converter/converter_test.go
- application/handler/user_info/user_info.go
- application/handler/user_signup/user_signup.go
- application/handler/user_withdraw/user_withdraw.go
- application/repository/sns.go
- application/service/alarm_test.go
- application/service/batch_test.go
- application/service/push_token_test.go
- application/service/user.go
- application/service/user_test.go
> 退会のタイミングでPlatformEndpointを削除するようにした

- application/handler/alarm_add/alarm_add.go
- application/handler/alarm_delete/alarm_delete.go
- application/handler/alarm_edit/alarm_edit.go
- application/handler/alarm_list/alarm_list.go
- application/handler/batch/batch.go
- application/handler/chara_id/chara_id.go
- application/handler/chara_list/chara_list.go
- application/handler/push_token_ios_push_add/push_token_ios_push_add.go
- application/handler/push_token_ios_voip_push_add/push_token_ios_voip_push_add.go
- application/handler/user_info/user_info.go
- application/handler/user_signup/user_signup.go
- application/handler/user_withdraw/user_withdraw.go
- application/repository/dynamodb.go
- application/repository/dynamodb_chara_test.go
- application/service/alarm.go
- application/service/alarm_test.go
- application/service/batch.go
- application/service/batch_test.go
- application/service/chara.go
- application/service/chara_test.go
- application/service/push_token.go
- application/service/push_token_test.go
- application/service/user.go
- application/service/user_test.go
> アラームの着信が変になっているので修正

- .github/workflows/deploy-for-sandbox.yml
- application/handler/alarm_add/alarm_add.go
- application/handler/batch/batch.go
- application/handler/push_token_ios_push_add/push_token_ios_push_add.go
- application/handler/push_token_ios_voip_push_add/push_token_ios_voip_push_add.go
- application/handler/worker/worker.go
- application/repository/sns.go
- application/repository/sqs.go
- application/repository/sqs_test.go
- application/service/alarm_test.go
- application/service/batch.go
- application/service/batch_test.go
- application/service/push_token.go
- application/service/push_token_test.go
- application/service/user.go
- application/service/user_test.go
- application/service/worker.go
> ServiceでRepositoryを参照するときはInterfaceを使うようにする

- .github/workflows/test-pull-request-to-develop-branch.yml
- application/converter/converter.go
- application/converter/converter_test.go
- application/response/chara.go
> response.CharaCallにファイル名を追加する

- .github/workflows/test-pull-request-to-develop-branch.yml
- script/build-deploy.sh
> Staticビルドに変更した

- application/handler/maintenance/maintenance.go
> メンテナンスフラグを falseに修正

- application/service/batch.go
> LogとEnableではない時の処理を追加

- application/response/chara.go
> スネークケースをキャメルケースに更新

- application/entity/ios_voip_push_alarm_info_sqs_message.go
- application/entity/ios_voip_push_sns_message.go
- application/service/batch.go
- application/service/worker.go
> CharaIDを追加

- .github/workflows/deploy-for-development.yml
- .github/workflows/deploy-for-production.yml
- .github/workflows/deploy-for-staging.yml
- terraform/resource/main.tf
- terraform/variables.tf
> デプロイスクリプトを追加

- terraform/lp/main.tf
- terraform/lp/variables.tf
- terraform/main.tf
- terraform/platform_application/variables.tf
- terraform/variables.tf
> 検証環境でも通知されるようにした

- terraform/lp/main.tf
> S3とCFの設定を変更

- terraform/github/main.tf
> GitHubAction用のIAM Roleに権限を追加

- .github/workflows/deploy-for-development.yml
- .github/workflows/deploy-for-production.yml
- .github/workflows/deploy-for-staging.yml
- .github/workflows/go-fmt-test.yml
- .github/workflows/remove-cloudfront-cache-for-development.yml
- .github/workflows/remove-cloudfront-cache-for-production.yml
- .github/workflows/remove-cloudfront-cache-for-staging.yml
- .github/workflows/test-pull-request-to-develop-branch.yml
* #108 の対応
* checkoutのアップデート
* fmtのエラー例
* https://github.com/takoikatakotako/charalarm-backend/actions/runs/6207642998
> chore: add gofmt and update checkout

- application/handler/healthcheck/healthcheck.go
- script/build-deploy.sh
- terraform/batch/main.tf
- terraform/web_api/lambda_function/main.tf
- terraform/web_api/lambda_function/variables.tf
- terraform/web_api/resource_alarm_add.tf
- terraform/web_api/resource_alarm_delete.tf
- terraform/web_api/resource_alarm_edit.tf
- terraform/web_api/resource_alarm_list.tf
- terraform/web_api/resource_chara_id.tf
- terraform/web_api/resource_chara_list.tf
- terraform/web_api/resource_healthcheck.tf
- terraform/web_api/resource_maintenance.tf
- terraform/web_api/resource_push_token_ios_push_add.tf
- terraform/web_api/resource_push_token_ios_voip_push_add.tf
- terraform/web_api/resource_require.tf
- terraform/web_api/resource_user_info.tf
- terraform/web_api/resource_user_signup.tf
- terraform/web_api/resource_user_update_premium.tf
- terraform/web_api/resource_user_withdraw.tf
- terraform/worker/main.tf
> Lambdaのランタイムを更新

- application/repository/dynamodb/dynamodb_chara.go
- application/service/chara.go
> Enableのもののみ有効にするように処理を追加
